### PR TITLE
AP6256: Update bluetooth firmware to version 0039.0089

### PR DESCRIPTION
**Pull request by floion**
This update makes the bluetooth on Radxa Zero function correctly

Signed-off-by: Florin Sarbu <florin@balena.io>

### CODE REVIEW

**Comment by jack-ma** [comment]
Hi, Florin

Just wondering, where is this bt firmware come from?

**Comment by floion** [comment]
Hi @jack-ma , I used it from Ubuntu

**Comment by jack-ma** [comment]
@floion which ubuntu, you mean upstream ubuntu?

**Comment by floion** [comment]
@jack-ma sorry, it was from Debian actually. From debian buster, not ubuntu

**Pull request merged**
